[package]
name = "avnu"
version = "1.0.0"
description = "Best execution on Starknet. No fluff."
homepage = "https://app.avnu.fi/"
cairo-version = "2.3.1"

[dependencies]
starknet = "2.3.1"

[[target.starknet-contract]]
sierra = true
casm = true
