[package]
name = "cairoswap"
version = "1.0.0"
description = "Best execution on Starknet. No fluff."
cairo-version = "2.3.1"

[dependencies]
starknet = "2.3.1"

[[target.starknet-contract]]
sierra = true
casm = true
